# Day-01 of 30 days of python
print(2+3)  # addition (+)
print(5-7)  # substraction (-)
print(5*3)  # multiplication (*)
print(18/6)  # division (/)
print(4**2)  # exponential (**)
print(3 % 2)   # modulus (%)
print(3//2)  # floor division operator (//)

# checking data types in python
print(type(10))
print(type(10.34))
print(type('manoj'))
print(type("manoj reddy"))
print(type(1+3j))
print(type(True))
print(type(False))
print(type(['manoj', 'mahi', 'python']))
print(type(2, 3, 4, 5))
print(type({'name': 'manojreddy', 'age': '25'}))
